# Lab 02: Manipulate PyTorch Tensors -- exercise

In [2]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/gdrive')
    file_name = 'pytorch_tensor_part1_exercise.ipynb'
    import subprocess
    path_to_file = subprocess.check_output('find . -type f -name ' + str(file_name), shell=True).decode("utf-8")
    print(path_to_file)
    path_to_file = path_to_file.replace(file_name,"").replace('\n',"")
    os.chdir(path_to_file)
    !pwd

In [3]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [16]:

# write your code here
A = torch.Tensor( [[1,2], [3,4]] )
B = torch.Tensor( [[10,20], [30,40]] )
C = A + B
print(C)


tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [17]:

# write your code here
print(A.dim())
print(A.size())
print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [18]:

# write your code here
A = A.long()
print(A.type())


torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [19]:

# write your code here
A = torch.rand(5,2,3)
print(A, '\n')
print(A.type(),'\n')
print(A.dim(), '\n')
print(A.size(), '\n')
print(A.size(1), '\n')


tensor([[[0.3027, 0.7093, 0.4380],
         [0.5074, 0.0826, 0.5419]],

        [[0.8826, 0.7337, 0.9555],
         [0.3317, 0.8209, 0.7698]],

        [[0.2590, 0.1312, 0.1132],
         [0.0460, 0.9927, 0.0722]],

        [[0.8769, 0.8436, 0.3024],
         [0.0934, 0.2494, 0.8765]],

        [[0.4738, 0.1376, 0.9198],
         [0.8779, 0.7058, 0.5215]]]) 

torch.FloatTensor 

3 

torch.Size([5, 2, 3]) 

2 



### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [14]:

# write your code here
A = torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
