# Lab 02 : GPU demo

In [1]:
import sys, os

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Set the device variable to be either cuda or cpu

In [7]:
device = torch.device("cpu")

# device = torch.device("cpu")

print(device)

cpu


### Make a random tensor (by default the tensor is create on the CPU)

In [8]:
x = torch.rand(3, 3)

print(x)

tensor([[0.0714, 0.7987, 0.3131],
        [0.7282, 0.8453, 0.7215],
        [0.5415, 0.9620, 0.6127]])


### Send the tensor to the device (which is going to be the GPU if the device was set to be the GPU -- otherwise it will remain on the CPU)

In [9]:
x = x.to(device)

print(x)

tensor([[0.0714, 0.7987, 0.3131],
        [0.7282, 0.8453, 0.7215],
        [0.5415, 0.9620, 0.6127]])


### Make a one layer net class

In [10]:
class one_layer_net(nn.Module):
    
    def __init__(self, input_size, output_size):
        super(one_layer_net, self).__init__()
        self.layer1 = nn.Linear(input_size, output_size, bias=False)
        
    def forward(self, x):
        scores = self.layer1(x)
        return scores

### Build the net

In [11]:
net = one_layer_net(5,2)
print(net)

one_layer_net(
  (layer1): Linear(in_features=5, out_features=2, bias=False)
)


### Send all the weights of the network to the GPU

In [12]:
net = net.to(device)

### Check that the matrix is indeed on the GPU

In [13]:
print(net.layer1.weight)

Parameter containing:
tensor([[-0.4428,  0.1490,  0.0112,  0.1430, -0.1454],
        [ 0.0079,  0.0453, -0.0246, -0.0406, -0.0092]], requires_grad=True)
