# Lab 01 : Linear module -- demo

In [1]:
import sys, os

In [2]:
import torch
import torch.nn as nn

### Make a *Linear Module* that takes input of size 5 and return output of size 3

In [3]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [4]:
x = torch.rand(5)
print(x)
print(x.size())

tensor([0.5457, 0.6848, 0.4426, 0.1911, 0.2353])
torch.Size([5])


### Feed it to the module:

In [5]:
y = mod(x)
print(y)

tensor([-0.0163, -0.0749, -0.2014], grad_fn=<AddBackward0>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2\\y_3
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be accessed as follow:

In [8]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[-0.2314,  0.1532,  0.1849,  0.2244, -0.3777],
        [-0.2203,  0.1120,  0.0961,  0.2379, -0.1625],
        [ 0.1410,  0.2506, -0.3904,  0.2614, -0.1818]], requires_grad=True)
torch.Size([3, 5])


In [10]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([-0.0308, -0.0811, -0.2844], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [12]:
mod.weight[0,0]=0
mod.weight[0,1]=1
mod.weight[0,2]=2
print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.2244, -0.3777],
        [-0.2203,  0.1120,  0.0961,  0.2379, -0.1625],
        [ 0.1410,  0.2506, -0.3904,  0.2614, -0.1818]], grad_fn=<CopySlices>)


### We can also make a Linear module without bias:

In [14]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [15]:
print(mod2.weight)

Parameter containing:
tensor([[-0.2364,  0.4191,  0.1667, -0.0165, -0.3267],
        [-0.1920,  0.3935, -0.1710, -0.3402, -0.3065],
        [ 0.2927,  0.3873,  0.0866, -0.1603,  0.3223]], requires_grad=True)


In [16]:
print(mod2.bias)

None
