# Lab 02 : Softmax function -- demo

In [2]:
import sys, os

In [3]:
import torch
import torch.nn.functional as F

### Make a vector

In [4]:
x = torch.Tensor([-2, -0.5, 2.0, 1.5])
print(x)
print(x.size())

tensor([-2.0000, -0.5000,  2.0000,  1.5000])
torch.Size([4])


### Feed it to the softmax

In [12]:
p = F.softmax(x, dim = 0)
print(p)
print(p.size())

tensor([0.0107, 0.0481, 0.5858, 0.3553])
torch.Size([4])


### Check that it sums to one

In [11]:
p = F.softmax(A, dim = 1)
2
print(0.0107+0.0481+0.5858+0.3553)
print(p.sum())

0.9999
tensor(1.)


### Make a matrix a matrix

In [15]:
A = torch.Tensor( [ [-2, -0.5, 2.0, 1.5], [-2, -0.5, 7.0, 1.5] ] )
print(A)
print(A.size())

tensor([[-2.0000, -0.5000,  2.0000,  1.5000],
        [-2.0000, -0.5000,  7.0000,  1.5000]])
torch.Size([2, 4])


### Take the softmax over the rows (dim=1)

In [18]:
p = F.softmax(A, dim = 1)
print(p)
print(p[0].sum())
print(p[1].sum())

tensor([[1.0730e-02, 4.8089e-02, 5.8585e-01, 3.5533e-01],
        [1.2282e-04, 5.5046e-04, 9.9526e-01, 4.0674e-03]])
tensor(1.)
tensor(1.)


### Take the softmax over the columns (dim=0)

In [19]:
p = F.softmax(A, dim = 0)
print(p)

tensor([[0.5000, 0.5000, 0.0067, 0.5000],
        [0.5000, 0.5000, 0.9933, 0.5000]])
