# Lab 01: Introduction to PyTorch

In [1]:
# For Google Colaboratory
import sys, os

In [2]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [4]:
x=torch.Tensor( [5.2 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.2000,  2.1000, -3.1000])


### Construct a 2 x 2 matrix

In [5]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [6]:
A=torch.rand(10,2)
print(A)

tensor([[0.2781, 0.2672],
        [0.4117, 0.0973],
        [0.3794, 0.3824],
        [0.2711, 0.0255],
        [0.0161, 0.5299],
        [0.7448, 0.5006],
        [0.4798, 0.1210],
        [0.2189, 0.1995],
        [0.6608, 0.7862],
        [0.9096, 0.6247]])


### Construct a 10 x 2 matrix filled with zeros

In [7]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor

In [17]:
B = torch.rand(5,2,2)
print(B, '\n')
print(B[0], '\n')
print(B[0][0], '\n')
print(B[0][0][0], '\n')
print(B[0][1][0], '\n')

tensor([[[0.4988, 0.0436],
         [0.0787, 0.9223]],

        [[0.3529, 0.7352],
         [0.4624, 0.0719]],

        [[0.7312, 0.1904],
         [0.2153, 0.8728]],

        [[0.5407, 0.3469],
         [0.0891, 0.4417]],

        [[0.1932, 0.5866],
         [0.0481, 0.6149]]]) 

tensor([[0.4988, 0.0436],
        [0.0787, 0.9223]]) 

tensor([0.4988, 0.0436]) 

tensor(0.4988) 

tensor(0.0787) 



In [9]:
B.size()

torch.Size([5, 2, 2])

In [10]:
B.dim()

3

In [11]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor

#### A 3-dimensional Tensor

In [18]:
A = torch.rand(3,2,2)
print(A)

tensor([[[0.6747, 0.9140],
         [0.7383, 0.0409]],

        [[0.4750, 0.1007],
         [0.1092, 0.7123]],

        [[0.1323, 0.8465],
         [0.0959, 0.1171]]])


In [20]:
print( A.dim() )

3


In [21]:
print( A.size() )

torch.Size([3, 2, 2])


In [22]:
print( A.size(0))

3


#### A 2-dimensional Tensor

In [23]:
B = torch.rand(3,5)
print(B)

tensor([[0.6548, 0.4451, 0.3355, 0.6384, 0.5642],
        [0.7173, 0.5491, 0.8933, 0.0995, 0.0032],
        [0.2941, 0.7146, 0.0407, 0.5454, 0.6274]])


In [24]:
print( B.dim() )

2


In [25]:
print( B.size() )

torch.Size([3, 5])


In [30]:
print( B.size(0) )

3


In [28]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [31]:
x=torch.rand(7)
print(x)

tensor([0.6654, 0.4915, 0.3507, 0.4957, 0.7494, 0.3884, 0.0542])


In [32]:
print( x.dim() )

1


In [33]:
print( x.size() )

torch.Size([7])


#### Adding and multiplying tensors

In [34]:
A = torch.rand(2,2)
B = torch.rand(2,2)

C = 2 * B
D = A + C
E = A * B

print(A, '\n')
print(B, '\n')
print(C, '\n')
print(D, '\n')
print(E, '\n')

tensor([[0.3568, 0.5139],
        [0.1643, 0.5237]]) 

tensor([[0.9903, 0.8455],
        [0.8388, 0.9133]]) 

tensor([[1.9806, 1.6910],
        [1.6776, 1.8266]]) 

tensor([[2.3374, 2.2049],
        [1.8418, 2.3504]]) 

tensor([[0.3533, 0.4345],
        [0.1378, 0.4783]]) 



In [38]:
A = torch.Tensor( [[1,2],[3,4]] )
B = torch.Tensor( [[5,6],[7,8]] )
C = A * B
print(A, '\n')
print(B, '\n')
print(C, '\n')

tensor([[1., 2.],
        [3., 4.]]) 

tensor([[5., 6.],
        [7., 8.]]) 

tensor([[ 5., 12.],
        [21., 32.]]) 



### Floats versus integers

In [39]:
x = torch.Tensor([1.2, 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [40]:
y = torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [41]:
y = y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [42]:
x = x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [43]:
x = torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [82]:
x = torch.randperm(10)
print(x)
print(x.type())

tensor([4, 1, 8, 5, 9, 7, 3, 0, 2, 6])
torch.LongTensor


In [83]:
x = torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication
torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [84]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [85]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [86]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [87]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [88]:
y = x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [89]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [90]:
print( y[0] )

tensor([0, 1])


In [91]:
print (y[1] )

tensor([2, 3])


In [92]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [93]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [94]:
print(y[1:4])

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [95]:
idx = 1
n = 3
print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let's check the sizes after slicing

In [96]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [97]:
z = y[1:1+3]
print(z, '\n')
print('dimension=', z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]]) 

dimension= 2
torch.Size([3, 2])
