# Lab 01: Introduction to PyTorch

In [6]:
# For Google Colaboratory
import sys, os

In [7]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [8]:
x=torch.Tensor( [5.2 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.2000,  2.1000, -3.1000])


### Construct a 2 x 2 matrix

In [9]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [10]:
A=torch.rand(10,2)
print(A)

tensor([[0.2952, 0.8533],
        [0.1738, 0.0866],
        [0.3663, 0.7276],
        [0.7284, 0.6873],
        [0.3127, 0.2363],
        [0.6062, 0.2455],
        [0.4419, 0.2867],
        [0.7285, 0.3686],
        [0.1455, 0.5317],
        [0.7171, 0.5494]])


### Construct a 10 x 2 matrix filled with zeros

In [11]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor

In [12]:
B = torch.rand(5,2,2)
print(B, '\n')
print(B[0], '\n')
print(B[0][0], '\n')
print(B[0][0][0], '\n')
print(B[0][1][0], '\n')

tensor([[[0.4442, 0.2922],
         [0.4334, 0.7254]],

        [[0.2526, 0.5527],
         [0.6330, 0.9971]],

        [[0.2634, 0.3541],
         [0.3151, 0.9254]],

        [[0.4871, 0.1253],
         [0.5175, 0.4242]],

        [[0.3792, 0.6564],
         [0.0479, 0.6893]]]) 

tensor([[0.4442, 0.2922],
        [0.4334, 0.7254]]) 

tensor([0.4442, 0.2922]) 

tensor(0.4442) 

tensor(0.4334) 



In [13]:
B.size()

torch.Size([5, 2, 2])

In [14]:
B.dim()

3

In [15]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor

#### A 3-dimensional Tensor

In [16]:
A = torch.rand(3,2,2)
print(A)

tensor([[[0.5824, 0.8550],
         [0.8238, 0.1423]],

        [[0.9566, 0.1749],
         [0.5552, 0.8095]],

        [[0.3047, 0.4308],
         [0.6604, 0.7590]]])


In [17]:
print( A.dim() )

3


In [18]:
print( A.size() )

torch.Size([3, 2, 2])


In [19]:
print( A.size(0))

3


#### A 2-dimensional Tensor

In [20]:
B = torch.rand(3,5)
print(B)

tensor([[0.9918, 0.3654, 0.0180, 0.0844, 0.3907],
        [0.5023, 0.0838, 0.7300, 0.5324, 0.0644],
        [0.1948, 0.2060, 0.2348, 0.6019, 0.9562]])


In [21]:
print( B.dim() )

2


In [22]:
print( B.size() )

torch.Size([3, 5])


In [23]:
print( B.size(0) )

3


In [24]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [25]:
x=torch.rand(7)
print(x)

tensor([0.6422, 0.8470, 0.7377, 0.5459, 0.9197, 0.5303, 0.6142])


In [26]:
print( x.dim() )

1


In [27]:
print( x.size() )

torch.Size([7])


#### Adding and multiplying tensors

In [28]:
A = torch.rand(2,2)
B = torch.rand(2,2)

C = 2 * B
D = A + C
E = A * B

print(A, '\n')
print(B, '\n')
print(C, '\n')
print(D, '\n')
print(E, '\n')

tensor([[0.1102, 0.8352],
        [0.4556, 0.0361]]) 

tensor([[0.3508, 0.2778],
        [0.7843, 0.6091]]) 

tensor([[0.7017, 0.5557],
        [1.5687, 1.2181]]) 

tensor([[0.8119, 1.3908],
        [2.0242, 1.2542]]) 

tensor([[0.0387, 0.2320],
        [0.3573, 0.0220]]) 



In [29]:
A = torch.Tensor( [[1,2],[3,4]] )
B = torch.Tensor( [[5,6],[7,8]] )
C = A * B
print(A, '\n')
print(B, '\n')
print(C, '\n')

tensor([[1., 2.],
        [3., 4.]]) 

tensor([[5., 6.],
        [7., 8.]]) 

tensor([[ 5., 12.],
        [21., 32.]]) 



### Floats versus integers

In [30]:
x = torch.Tensor([1.2, 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [31]:
y = torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [32]:
y = y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [33]:
x = x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [34]:
x = torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [35]:
x = torch.randperm(10)
print(x)
print(x.type())

tensor([4, 3, 2, 0, 1, 6, 8, 9, 7, 5])
torch.LongTensor


In [36]:
x = torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication
torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [37]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [38]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [39]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [40]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [41]:
y = x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [42]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [43]:
print( y[0] )

tensor([0, 1])


In [44]:
print (y[1] )

tensor([2, 3])


In [45]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
print(y[1:4])

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [48]:
idx = 1
n = 3
print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let's check the sizes after slicing

In [49]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [50]:
z = y[1:1+3]
print(z, '\n')
print('dimension=', z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]]) 

dimension= 2
torch.Size([3, 2])


In [51]:
v = y[1]
print(v, '\n')
print('dimension=', v.dim())
print(v.size())

tensor([2, 3]) 

dimension= 1
torch.Size([2])


### Accessing the entries of a Tensor

In [52]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [53]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [55]:
a = y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [56]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor

### A row of matrix is a 1-dimensional Tensor

### An entry of a matrix is a 0-dimensional Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into python number, we need to use item()

In [57]:
b = a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
