# Lab 03 : Vanilla neural networks -- exercise

# Creating a one-layer network

In [11]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/gdrive')
    file_name = 'vanilla_nn_exercise.ipynb'
    import subprocess
    path_to_file = subprocess.check_output('find . -type f -name ' + str(file_name), shell=True).decode("utf-8")
    print(path_to_file)
    path_to_file = path_to_file.replace(file_name,"").replace('\n',"")
    os.chdir(path_to_file)
    !pwd

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [3]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        
        # complete here
        self.mylayer = nn.Linear(input_size, output_size, bias = True)        
        
    def forward(self, x):
        x = self.mylayer(x)
        x = F.relu(x)
        p = F.softmax(x, dim = 0)
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [4]:
net = one_layer_net(2,2)
print(net)

one_layer_net(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability? Check that it sums to one.

In [7]:
x = torch.Tensor([1,1])
print(x)

p = net(x)
print(p)

print(p.sum() )

tensor([1., 1.])
tensor([0.6350, 0.3650], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [8]:
print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[ 0.5666,  0.2048],
        [-0.2008,  0.3391]], requires_grad=True)
Parameter containing:
tensor([-0.2178, -0.2428], requires_grad=True)


### Change the internal parameters of your network so that the weights are now equal to $
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [9]:
# CHANGE THE WEIGHTS
net.mylayer.weight[0,0] = 1
net.mylayer.weight[0,1] = 2
net.mylayer.weight[1,0] = 3
net.mylayer.weight[1,1] = 4

# CHANGE THE BIAS
net.mylayer.bias[0] = 1
net.mylayer.bias[1] = 1

print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[1., 2.],
        [3., 4.]], grad_fn=<CopySlices>)
Parameter containing:
tensor([1., 1.], grad_fn=<CopySlices>)


### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [10]:
p = net(x)
print(p)

tensor([0.0180, 0.9820], grad_fn=<SoftmaxBackward>)
